name: Maven Verify (Coverage)

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Build & test (verify with coverage)
        run: ./mvnw -B -ntp verify

      - name: Upload JaCoCo XML
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jacoco-xml
          path: |
            **/target/site/jacoco/jacoco.xml
            **/target/site/jacoco-merge/jacoco.xml
            **/target/site/jacoco-aggregate/jacoco.xml
          if-no-files-found: warn
          retention-days: 14

      - name: Upload JaCoCo HTML
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jacoco-html
          path: |
            **/target/site/jacoco/*
            **/target/site/jacoco-merge/*
            **/target/site/jacoco-aggregate/*
          if-no-files-found: warn
          retention-days: 14